<a href="https://colab.research.google.com/github/TalCordova/TensorFlow_Course/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook we are going to cover some of the most fundumentals of tensors using TensorFlow

More specifically, we are going to cover
* Intro to tensors
* Geting information from tensors
* Manipulating tensors
* Tensors & NumPy
* Using @tf.function (a way to speed up your regular python functions)
* Using GPUs with TensorFlow
* Exercises for myself.

## Introduction to tensors

In [ ]:
# Imort TensorFlow
import tensorflow as tf
print(tf.__version__)

2.9.2


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor (ndim  stands for number of dimensions)
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10, 10])
vector 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#Check the dimensions of our vector
vector = vector.ndim

In [ ]:
matrix = tf.constant([[10, 7], 
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix
another_matrix = tf.constant([[10.,7.],
                              [3., 2.],
                              [8., 9.]], dtype = tf.float16) # specify data type with dtype parameter
another_matrix                      

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# What's the number of dimension of another matrix?
another_matrix.ndim

2

In [ ]:
# Let's create a tesnsor
tensor = tf.constant([[[1, 2, 3],
                      [4,5,6]],
                     [[7,8,9],
                      [10, 11, 12]],
                     [[13, 14, 15],
                      [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

from tensorflow.python.ops.math_ops import numbers
What we have craeted so far:
* Scalar: a single number* 
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a s-d arrat of numbers
* Tensor: an n-dimensional array of numbers (where n can be any number, a 0-dim tensor is a scalar, a 1-dim tensor is a vector)

### Creating tensors with tf.variable

In [ ]:
# Create the same tensot with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Let's try change one of the elements in the changeable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [ ]:
# Let's try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Let's try to change the unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

### Creating random tensors

Random tensors are tensors of arbitrary size with random numbers

In [ ]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(7) # set seed for reproduceability
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3,2))

# Are they equal?
random_1, random_2, random_1 == random_2

### Shuffle the order of elements in a tensor

In [ ]:
# Shuffle a tensor (valuable for when you want to shuffle your data, so inherent order doen's affect learning)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
not_shuffled
## shulle our not shuffled
tf.random.shuffle(not_shuffled)

In [ ]:
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffled) # operation level random seed

### Other ways to make tensros

In [ ]:
# Create a tensor of all ones
tf.ones([10,7])

In [ ]:
# Create a tensor of all zeros
tf.zeros(shape = (3,4))

### Turn NumPy arrays into tensors
The main difference between NumPy arrays and TensorFlow tensors in that tensors can be run on a GPU (much faster for numerical computers).

In [ ]:
from tensorflow.python.training.tracking.base import no_automatic_dependency_tracking
# You can also turn NumPy arrays to tf tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype = np.int32) ## create NumPy array between 1 and 25
numpy_A

# X = tf.constant(some_matrix) # capital for matrix
# y = tf.constant(vector) # non-capital for vector

In [ ]:
A = tf.constant(numpy_A, shape = (3, 8))
B = tf.constant(numpy_A)
A, B

### Getting information from tensors 

When dealing with tensors you probably want to be aware of the following attributes

* Shape
* Rank
* Axis or Dimension
* Size

In [ ]:
# Create a rank 4 tensor(4 dimensions)
rank_4_tensor = tf.zeros(shape = [2, 3, 4, 5])
rank_4_tensor

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

In [ ]:
# Get various attributes of a tensor
print("Datatype of every elemnt:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elemnts along the 0 axis:", rank_4_tensor.shape[0])
print("Elemnts alomg the last axis:", rank_4_tensor.shape[-1])
print("Total number of elemnts in our tensor:", tf.size(rank_4_tensor))
print("Total number of elemnts in our tensor:", tf.size(rank_4_tensor).numpy())

### Indexing tensors

Tensors can be indexed just like Python lists

In [ ]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

In [ ]:
# Get the first element each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

In [ ]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim
rank_2_tensor

In [ ]:
# Get the last item of each row of our rank  sector
rank_2_tensor[:, -1]

In [ ]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

In [ ]:
 # Alternative to tf.newaxis
 tf.expand_dims(rank_2_tensor, axis =-1)

In [ ]:
# Expand 0 axis
tf.expand_dims(rank_2_tensor, axis = 0)

### Manipulating tensors (tensor operations)

** Basic operations

`+`, `-`, `*`, `:`

In [ ]:
## You can add valuses to a tensor using the addition operator
tensor = tf.constant([[10, 7],
                      [3, 4]])
tensor + 10

In [ ]:
# Original tensor is unchaned
tensor

In [ ]:
# Multiplication also works
tensor*10

In [ ]:
# Subtraction
tensor-10

In [ ]:
# We can use the tensoflow built in function
tf.multiply(tensor, 10)

In [ ]:
tensor

In [ ]:
tf.add(tensor, 10)

**Matrix Multiplication**

In machine learning matrix multiplication is one of the most common tensor operations.

There are two rules that tensors needs to fulfill if we're going to matrix multiply them:
1. The inner dimensions must match
2. The resulting matrix has the shape of the outer dimensions

In [ ]:
# Matrix multiplication in tensorflow
print(tensor)
tf.matmul(tensor, tensor)

In [ ]:
#Matrix multiplication ptyhon has operaor "@"
tensor*tensor # element by elemnt multiplication
tensor@tensor

In [ ]:
# Create a tensor of (3,2)
tensor_1 = tf.constant([[1, 2, 5],
                        [7, 2, 1],
                        [3, 3, 3]])
X = tf.constant([[1, 2],
                [3, 4],
                [5, 6]])

#Create another (3,2) tensor
Y = tf.constant([[7, 8],
                [9, 10],
                [11, 12]])

In [ ]:
# Change the shape of Y
tf.reshape(Y, shape=(2,3))

In [ ]:
Y

In [ ]:
# Try to multipltly X by reshaped Y
X.shape, tf.reshape(Y, shape = (2,3)).shape

In [ ]:
X @ tf.reshape(Y, shape = (2,3))

In [ ]:
tf.matmul(X, tf.reshape(Y, shape = (2,3)))

In [ ]:
# Try change the shape of X instead of Y
tf.matmul(tf.reshape(X, shape = (2,3)), Y)

In [ ]:
tf.reshape(X, shape = (2,3)).shape, Y.shape

In [ ]:
# Can do the same with transpose
X, tf.transpose(X), tf.reshape(X, shape = (2,3))

In [ ]:
# Try multiplication with transpose rather tahn reshape
tf.matmul(tf.transpose(X), Y)

**The dot product**
Matrix multiplication is also reffered to as the dot product.

You can preform matrix multiplication using:
* `tf.mamul()`
* `tf.tensordot`

In [ ]:
X, Y

In [ ]:
# Preform dot product on X and Y (require X or Y to be transposed)
tf.tensordot(tf.transpose(X), Y, axes = 1)

In [ ]:
# Perform matrix multiplication between X and Y transpose
tf.matmul(X, tf.transpose(Y))

In [ ]:
# Preform matrix multiplication betwenn X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape = (2,3)))

In [ ]:
# Check the values of Y, reshape and transposed Y
print("Normal Y:")
print(Y, "\n")

print("Y reshaped to (2,3):")
print(tf.reshape(Y, shape = (2,3)), "\n")

print("Y Trnasposed")
print(tf.transpose(Y))

In [ ]:
tf.matmul(X, tf.transpose(Y))

Generally when preforming matrix multiplication on two tensors, and one of the axes does'nt line up, you will transpose (rather than reshape the tensors) to satisfy matrix multiplication rules.

### Changing the data type of a tensor

In [ ]:
# Create new tensor with default datatype (float 32)
B = tf.constant([1.7, 7.4])
B, B.dtype

In [ ]:
C = tf.constant([7, 10])
C.dtype

In [ ]:
# Change from float32 to float16
D = tf.cast(B, dtype = tf.float16)
D, D.dtype

In [ ]:
# Change from int32 to float32
E = tf.cast(C, dtype = tf.float32)
E

In [ ]:
E_float16 = tf.cast(E, dtype=tf.float16)
E_float16

### Aggregating Tensors

Aggregating tensors = densing from multiple values to smaller amount of values.

In [ ]:
# Get the absolute values
D = tf.constant([-7, -10])
D

In [ ]:
# Get the absolute values
tf.abs(D)

Let's go through the following form of aggregation
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of tensor


In [ ]:
# Create a random tensor with values between 0 to a 100 of size 50
E = tf.constant(np.random.randint(0, 100, size = 50))
E

In [ ]:
tf.size(E), E.shape, E.ndim

In [ ]:
# Find the minimum
tf.reduce_min(E)

In [ ]:
np.min(E)

In [ ]:
# Find the maximum
tf.reduce_max(E)

In [ ]:
# Find the mean
tf.reduce_mean(E)

In [ ]:
# Find the sum 
tf.reduce_sum(E)

In [ ]:
# Find the variance

In [ ]:
tf.math.reduce_std(tf.cast(E, dtype = tf.float32))

In [ ]:
tf.math.reduce_variance(tf.cast(E, dtype = tf.float32))

### Find positional maximum and minimum of a tensor

In [ ]:
# Create a new tnsor for finding positinal minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape = [50])
F

In [ ]:
# Find the posisitional maximum
tf.argmax(F)

In [ ]:
# Index on our largest value position
F[tf.argmax(F)]

In [ ]:
# Find max value in F
tf.reduce_max(F)

In [ ]:
# Check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

In [ ]:
# Find the positional minimum
tf.argmin(F)

In [ ]:
# Fine the minimum using positional minimum index
F[tf.argmin(F)]

### Squeezing a tensor (removing all single dimensions)

In [ ]:
# Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape = [1, 1, 1, 1, 50])
G

In [ ]:
G.shape

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

### One-hot encoding tensors

In [ ]:
# Create a lost of indices
some_list = [0, 1, 2, 3] # could be red, green, blue, purple

# One hot encode our list of indices
tf.one_hot(some_list, depth = 4)

In [ ]:
# Specify custom values for one-hot encoding
tf.one_hot(some_list, depth = 4, on_value="yo yo", off_value="mip mip")

### Squaring, log and square root

In [ ]:
# Create a new tensor
H = tf.range(1, 10)
H

In [ ]:
# Square
tf.square(H)

In [ ]:
# Square root - method requires non-int type
tf.sqrt(tf.cast(H, dtype = tf.float32))

In [ ]:
# Find the log
tf.math.log(tf.cast(H, dtype=tf.float32))

### Tensors and NumPy
TensorFlow interacts beautifully with NumPy arrays.

In [ ]:
# Create a tensor directly from a NumPy array
J = tf.constant(np.array([3., 7., 10.]))
J

In [ ]:
np.array(J), type(np.array(J))

In [ ]:
# Convert tensor J to NumPy array
J.numpy(), type(J.numpy())

In [ ]:
J = tf.constant([3.])
J.numpy()[0]

In [ ]:
# The defualt types of each are slightly different
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])

numpy_J.dtype, tensor_J.dtype

### Finding access to GPUs

In [ ]:
import tensorflow as tf
tf.config.list_logical_devices("GPU")

[LogicalDevice(name='/device:GPU:0', device_type='GPU')]

### Extra Curiculum

In [ ]:
# 1. Create a vector, scalar matrix and tensor
# 2. Find shape, rank and size
scalar_1 = tf.constant(7)
scalar_1, scalar_1.shape, scalar_1.ndim, tf.size(scalar_1)

(<tf.Tensor: shape=(), dtype=int32, numpy=7>,
 TensorShape([]),
 0,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [ ]:
vector_1 = tf.constant([3, 2])
vector_1, vector_1.shape, vector_1.ndim, tf.size(vector_1)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>,
 TensorShape([2]),
 1,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [ ]:
matrix_1 = tf.constant([[3, 2],
                        [5, 4]])
matrix_1, matrix_1.shape, matrix_1.ndim, tf.size(matrix_1)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[3, 2],
        [5, 4]], dtype=int32)>,
 TensorShape([2, 2]),
 2,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [ ]:
tensor_1 = tf.constant([[[1, 2],
                        [3,4]],
                        [[5,6],
                        [7,8]]])
tensor_1, tensor_1.shape, tensor_1.ndim, tf.size(tensor_1)

(<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
 array([[[1, 2],
         [3, 4]],
 
        [[5, 6],
         [7, 8]]], dtype=int32)>,
 TensorShape([2, 2, 2]),
 3,
 <tf.Tensor: shape=(), dtype=int32, numpy=8>)

In [ ]:
# 3. Create two random tensors of shape [5, 300]
tf.random.set_seed(42)
X = tf.random.uniform(shape= [5,300], minval = 0, maxval = 1)
Y = tf.random.uniform(shape = [5,300], minval = 0, maxval = 1)
X, Y

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.6645621 , 0.44100678, 0.3528825 , ..., 0.31410468, 0.7593535 ,
         0.03699052],
        [0.532024  , 0.29129946, 0.10571766, ..., 0.54052293, 0.31425726,
         0.2200619 ],
        [0.08404207, 0.03614604, 0.97732127, ..., 0.21516645, 0.9786098 ,
         0.00726748],
        [0.7396945 , 0.6653172 , 0.0787828 , ..., 0.7117733 , 0.07013571,
         0.9409125 ],
        [0.15861344, 0.12024033, 0.27218235, ..., 0.8824879 , 0.1432488 ,
         0.44135118]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.68789124, 0.48447883, 0.9309944 , ..., 0.6920762 , 0.33180213,
         0.9212563 ],
        [0.27369928, 0.10631859, 0.6218617 , ..., 0.4382149 , 0.30427706,
         0.51477313],
        [0.00920248, 0.37280262, 0.8177401 , ..., 0.56786287, 0.49201214,
         0.9892651 ],
        [0.88608265, 0.08672249, 0.12160683, ..., 0.91770685, 0.72545695,
         0.8280058 ],
        [0.36690

In [ ]:
# 4. Matrix multiply
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.333435, 73.40498 , 77.15961 , 73.98368 , 80.90053 ],
       [75.14637 , 68.80438 , 74.24303 , 71.84184 , 75.60205 ],
       [79.7594  , 75.64456 , 77.79758 , 74.748726, 80.55984 ],
       [75.085266, 69.06408 , 74.30776 , 72.27615 , 76.05667 ],
       [85.05689 , 74.26629 , 78.00687 , 74.886795, 83.13417 ]],
      dtype=float32)>

In [ ]:
# 5. Dot product
tf.tensordot(X, Y, axes = 0)

<tf.Tensor: shape=(5, 300, 5, 300), dtype=float32, numpy=
array([[[[4.57146466e-01, 3.21966261e-01, 6.18703604e-01, ...,
          4.59927619e-01, 2.20503122e-01, 6.12232029e-01],
         [1.81890175e-01, 7.06553087e-02, 4.13265705e-01, ...,
          2.91221023e-01, 2.02211007e-01, 3.42098713e-01],
         [6.11561956e-03, 2.47750491e-01, 5.43439090e-01, ...,
          3.77380133e-01, 3.26972634e-01, 6.57428086e-01],
         [5.88856936e-01, 5.76324835e-02, 8.08152854e-02, ...,
          6.09873176e-01, 4.82111186e-01, 5.50261259e-01],
         [2.43830979e-01, 6.11405969e-01, 6.41095340e-01, ...,
          4.58627582e-01, 4.74320024e-01, 1.71758875e-01]],

        [[3.03364694e-01, 2.13658452e-01, 4.10574824e-01, ...,
          3.05210292e-01, 1.46326989e-01, 4.06280279e-01],
         [1.20703243e-01, 4.68872190e-02, 2.74245232e-01, ...,
          1.93255737e-01, 1.34188250e-01, 2.27018446e-01],
         [4.05835640e-03, 1.64408475e-01, 3.60628933e-01, ...,
          2.50431389e-0

In [ ]:
# 6. Generate random tensor of shape [224, 224, 3]
Z = tf.random.uniform(shape = [224, 224, 3], minval = 0, maxval = 1)
Z

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[7.4023080e-01, 3.3938193e-01, 5.6925058e-01],
        [4.4811392e-01, 2.9285502e-01, 4.2600560e-01],
        [6.2890387e-01, 6.9106102e-01, 3.0925727e-01],
        ...,
        [9.1063976e-04, 6.9863999e-01, 1.7180574e-01],
        [6.7542684e-01, 8.3492923e-01, 3.9038682e-01],
        [2.3664141e-01, 6.2239432e-01, 1.0117912e-01]],

       [[9.7064960e-01, 5.4594779e-01, 7.6819682e-01],
        [2.6893330e-01, 2.6959443e-01, 2.8982997e-01],
        [2.9215467e-01, 1.7108858e-01, 6.5597153e-01],
        ...,
        [9.5621395e-01, 5.4591870e-01, 5.3843534e-01],
        [9.8861516e-01, 1.5786767e-01, 6.1375093e-01],
        [7.2668612e-01, 6.1637163e-03, 1.6534305e-01]],

       [[6.4095867e-01, 7.6697862e-01, 3.0138540e-01],
        [1.5474892e-01, 1.7183411e-01, 2.7192724e-01],
        [3.1211805e-01, 6.1451709e-01, 4.3001354e-01],
        ...,
        [8.4168065e-01, 5.0247252e-01, 2.8834987e-01],
        [3.3173549e-01

In [ ]:
# Find min and max along first axis
tf.reduce_min(Z, axis = 0)

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[2.03430653e-03, 4.37009335e-03, 3.90768051e-04],
       [3.51417065e-03, 7.98487663e-03, 3.59594822e-03],
       [6.48093224e-03, 2.49707699e-03, 8.29935074e-04],
       [1.56582594e-02, 7.75694847e-04, 9.87851620e-03],
       [5.94484806e-03, 1.92798376e-02, 5.68044186e-03],
       [1.93202496e-03, 4.99880314e-03, 6.75463676e-03],
       [7.42089748e-03, 8.29935074e-04, 2.86221504e-04],
       [4.54080105e-03, 4.18329239e-03, 9.62257385e-04],
       [9.15646553e-04, 4.49621677e-03, 3.66115570e-03],
       [1.78742409e-03, 4.46248055e-03, 7.77256489e-03],
       [3.64875793e-03, 3.26538086e-03, 7.45463371e-03],
       [5.15615940e-03, 2.73168087e-03, 1.84178352e-04],
       [3.78739834e-03, 2.19345093e-05, 2.04169750e-03],
       [1.40672922e-02, 1.87754631e-04, 2.32815742e-04],
       [8.25285912e-04, 2.10213661e-03, 1.35517120e-03],
       [4.73082066e-03, 7.74383545e-04, 1.39951706e-03],
       [3.03184986e-03, 1.41239166e-03

In [ ]:
tf.reduce_max(Z, axis = 0)

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[0.999496  , 0.9963497 , 0.9888816 ],
       [0.9986012 , 0.99141884, 0.9950535 ],
       [0.997959  , 0.97667074, 0.9986603 ],
       [0.99689543, 0.99890375, 0.9978107 ],
       [0.9857353 , 0.9985192 , 0.9993119 ],
       [0.9998385 , 0.99915946, 0.99280477],
       [0.9994391 , 0.99572384, 0.995831  ],
       [0.9947666 , 0.98579705, 0.99513376],
       [0.99427724, 0.99754584, 0.9998121 ],
       [0.99203503, 0.99756145, 0.9958385 ],
       [0.99305665, 0.9890835 , 0.99911284],
       [0.9945315 , 0.9968053 , 0.99750936],
       [0.99853754, 0.99238455, 0.9903239 ],
       [0.9986687 , 0.99331665, 0.9950056 ],
       [0.9967083 , 0.9971876 , 0.99862325],
       [0.99219584, 0.99877846, 0.98672354],
       [0.99661255, 0.9858984 , 0.99987435],
       [0.99535847, 0.9920274 , 0.981122  ],
       [0.9940791 , 0.9999418 , 0.9879633 ],
       [0.991364  , 0.9968468 , 0.9968897 ],
       [0.99629796, 0.99595034, 0.99858797],
     

In [ ]:
# Create random tensor with shape [1, 224, 224, 3]
A = tf.random.uniform(shape = [1, 224, 224, 3], minval = 0, maxval = 1)
A

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[8.0315602e-01, 4.9777734e-01, 3.7054038e-01],
         [9.1186738e-01, 6.3764203e-01, 1.8209696e-01],
         [6.3791955e-01, 2.7701473e-01, 4.2271137e-02],
         ...,
         [1.0830712e-01, 4.5979273e-01, 2.5716281e-01],
         [8.7138689e-01, 1.8434000e-01, 4.4757760e-01],
         [7.4110627e-02, 9.0852141e-01, 5.3693414e-01]],

        [[5.5596435e-01, 6.8776274e-01, 7.6051474e-02],
         [1.6737962e-01, 7.1785092e-01, 2.7642274e-01],
         [2.6995218e-01, 3.2203627e-01, 8.8224900e-01],
         ...,
         [4.8168826e-01, 5.0150025e-01, 8.6756039e-01],
         [4.1261053e-01, 1.2770486e-01, 5.8186901e-01],
         [2.5495613e-01, 3.9036548e-01, 9.8529553e-01]],

        [[8.0935180e-01, 1.9740558e-01, 3.5899937e-01],
         [1.1216915e-01, 9.1016293e-04, 3.6382091e-01],
         [5.1202202e-01, 3.9188230e-01, 8.8335538e-01],
         ...,
         [2.0133841e-01, 9.1663551e-01, 1.9890130e-01],


In [ ]:
# 8. Squeeze the tensor
A_squeezed = tf.squeeze(A)
A_squeezed.shape

TensorShape([224, 224, 3])

In [ ]:
B = tf.random.uniform(shape = [10])
B

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.95831835, 0.01680839, 0.3156035 , 0.16013157, 0.7148702 ,
       0.7892921 , 0.11484027, 0.33310425, 0.21091413, 0.62329304],
      dtype=float32)>

In [ ]:
# 9. Find index of maximum value
tf.argmax(B)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
# 10. One-hot encode B
C = tf.constant(np.arange(0, 10))
C

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [ ]:
tf.one_hot(C, 10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>